# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsched_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostgroup',
            name='host_group_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='host_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
