# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsched_admin', '0002_auto_20170322_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='cluster_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='host_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vm',
            name='vm_id',
            field=models.IntegerField(default=0),
        ),
    ]
