# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsched_admin', '0003_auto_20170328_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='host_id',
        ),
    ]
