# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsched_admin', '0005_auto_20170329_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostgroup',
            name='host_id',
        ),
    ]
